# Site settings
title: 大迷毛
email: 1061822690@qq.com
description: 大迷毛
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.xulirong.cn/" # the base hostname & protocol for your site
twitter_username: 
github_username:  xulirong

# Build settings
markdown: kramdown
encoding: utf-8

theme: jekyll-theme-cayman